### ISSUE TITLE
Improved UX for dashboard filter eligibility [SIP-45]

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#10]
## Motivation / Problem to Solve
Currently a user can configure dashboard filters to either apply (enabled; the chart is non-immune to the filter) or not apply (disabled; the chart is immune to the filter) to specific charts. For the former there is no validation on whether the filter is eligible, i.e., can be applied to the datasource, for the specific chart and currently if the filter is deemed irrelevant it is simply ignored by the chart. The issue with this approach is there is no visual indication that the chart has ignored said filter(s) and thus the viewer could be misguided into believing a set of filters have been applied, thus making an incorrect conclusion.

See [SIP-45](https://github.com/apache/incubator-superset/issues/9935) for more details

## Proposed Solution
The root problem is there is no validation if enabled filters are actually eligible for said charts. The SIP proposes two options. 

See [SIP-45](https://github.com/apache/incubator-superset/issues/9935) for more details

**Comment by junlincc** [comment]
completed for 1.0 
Tasks for next iteration:
1) improve the indicator styling 
2) include Ad hoc filter section 
3) include Jinja filter status
