### ISSUE TITLE
[explore]collapsible data left panel

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#101]
![101228683-97163d00-3651-11eb-97ab-be76a6da3e01](https://user-images.githubusercontent.com/67837651/101688649-2ab88680-3a21-11eb-8ef6-c60755a52cad.gif)

**Comment by geido** [comment]
I'd be taking this. Should be a relatively quick win.

**Comment by junlincc** [comment]
> I'd be taking this. Should be a relatively quick win.

Thanks Diego, this one is completed for Superset 1.0. Next iteration will be resizable panels, would you like to take that one on instead?

**Comment by geido** [comment]
> > I'd be taking this. Should be a relatively quick win.
> 
> Thanks Diego, this one is completed for Superset 1.0. Next iteration will be resizable panels, would you like to take that one on instead?

Sure why not @junlincc

**Comment by junlincc** [comment]
completed
