### ISSUE TITLE
[global] add undo feature after deleting objects 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#103]
As a superset user, I want to undo my delete from list view so that I can recover objects that 1)I regret deleting 2)accidentally deleted by myself or others in my workspace. 

Related issue: https://github.com/apache/incubator-superset/issues/11933

I am proposing adding an "Undo" feature as a post 1.0 roadmap item in global.

**Comment by ktmud** [comment]
What you need is a Recycle Bin or Trash feature. Entities should have a "deleted" state in addition to "draft".

**Comment by maloun96** [comment]
I can take this one. My suggestion is to remove confirm modal and add a "UNDO" on the notification below
![image](https://user-images.githubusercontent.com/8277264/103674053-f637dc00-4f86-11eb-88a8-fb730c9b78d9.png)

Like google: 
![image](https://user-images.githubusercontent.com/8277264/103674139-136caa80-4f87-11eb-9e0b-995c59ae8fdb.png)

@ktmud @junlincc

**Comment by ktmud** [comment]
@maloun96 Another solution (which I personally would prefer) is "in place UNDO". I.e. replace the deleted row/card with a placeholder that gradually fadeout and has a UNDO link on it (E.g. could mask the row with "XXX has been deleted. UNDO"). Might need a design mockup for this though.

Either way, feel free to pick this up!

**Comment by junlincc** [comment]
@benceorlai If it's ok with you, @ktmud @maloun96 and I will collaborate on this GLOBAL feature as a follow up solution of an (intense🤦🏾‍♀️) conversation last month https://github.com/apache/superset/issues/11933 

cc @mistercrunch @nytai

**Comment by junlincc** [comment]
we anticipate some B/E work to be done for deleted state right? @nikolagigic

**Comment by nikolagigic** [comment]
> we anticipate some B/E work to be done for deleted state right? @nikolagigic

This depends on how B/E handles deletion of objects and how does F/E pulls objects - will have a further look into this. I can help out/share work with @maloun96 for this one or take it over to work on it if its more appropriate

**Comment by junlincc** [comment]
@maloun96 Hey Victor, I'm changing task ownership to Michael, you can focus on chart enhancement. 🙏
