### ISSUE TITLE
[dashboard]integrate new ad hoc time picker in native dashboard 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#104]
^
https://github.com/apache/incubator-superset/pull/11418

**Comment by junlincc** [comment]
[dashboard]native filter sidebar styling and width should be consistent with the Data panel in Explore
Explore
<img width="281" alt="Screen Shot 2020-12-21 at 12 30 50 AM" src="https://user-images.githubusercontent.com/67837651/102756034-21ce8b80-4324-11eb-9d90-74baf13a7749.png">
Native filter 
<img width="81" alt="Screen Shot 2020-12-21 at 12 32 10 AM" src="https://user-images.githubusercontent.com/67837651/102756038-2430e580-4324-11eb-9f57-5d5f42348156.png">

**Comment by junlincc** [comment]
Need design input, top priority early Q1
Designer: @mihir174 
Engineer: @zhaoyongjie

**Comment by geido** [comment]
Nice community contribution over there. I'd love to take over this.

**Comment by zhaoyongjie** [comment]
nice meeting you Diego, glad to collaborate with you on the Superset.

**Comment by junlincc** [comment]
Proposed design(by @mihir174) - Dashboard native filter modals with time column select 
After selecting time column and time grain in the modal, a pill will appear on the the left filter bar, click to open the same ad hoc timepicker in Explore. 

<img width="1456" alt="Filters_Columns" src="https://user-images.githubusercontent.com/67837651/105942520-37fef400-6014-11eb-80e4-979c6b01cd43.png">
<img width="1456" alt="Filters_Time" src="https://user-images.githubusercontent.com/67837651/105942522-3af9e480-6014-11eb-9456-5fd60a86a7b6.png">

@zhaoyongjie @graceguo-supercat @mistercrunch @villebro @ktmud 
we are not sure about if we can deprecate `Show SQL Granularity Dropdown`, `Show SQL Time Column`, `Show Druid Granularity Dropdown` and `Show Druid Time Origin` these four check boxes, risks, cost, alternative solutions etc. please let us know. Thanks! 
<img width="336" alt="Screen Shot 2021-01-26 at 8 26 37 PM" src="https://user-images.githubusercontent.com/67837651/105943087-629d7c80-6015-11eb-8127-2378927561f0.png">

**Comment by villebro** [comment]
Both Druid options should be deprecated, but "SQL Granularity Dropdown" and "SQL Time Column" should be separate native filters, much like the Select, Range and Time Picker filters are (they only differ in the options and what types of values they emit).
