### ISSUE TITLE
[system] Superset can be configured by a URL Prefix 

### ISSUE THREAD

**Issue by cdmikechen** [apache-superset/superset-roadmap#105]
### Motivation / Problem to Solve
Links to questions can be referred to https://github.com/apache/incubator-superset/issues/3690 .
We encountered this problem when deploying superset to the ingress of k8s. Some of our services are based on non host mode and need to be identified by path. There is no unified path for superset, so it cannot be processed in nginx ingress.

### Proposed Functionality
Suggest that the URL path of superset can be based on a configured `URL Prefix`, so that it can be configured in nginx or some other gateway easily.

**Comment by Moofasax** [comment]
any updates on this?

**Comment by cdmikechen** [comment]
@Moofasax  
I created a new branch myself to try to fix this problem. Base on my experience, there are many things that need to be changed, including many configuration adjustments of flask and customizing some new inherited classes to implement new routes. And then the frontend code needs to modify all url paths based on rest api, which is a very heavy workload. The last is how to make the webpack tool compile files according to the relative path to support the customization of the file path.

**Comment by abeep** [comment]
Any updates on this?

**Comment by mrgokul** [comment]
Hi @junlincc , Can you please update on this issue? We are unable to use superset because we require a URL prefix.
