### ISSUE TITLE
[homescreen]add object types filter to Recent section 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#106]
To offer users the flexibility to filter cards in Homescreen Recents by object types(dashboard, charts and saved queries)

cc: @mihir174

**Comment by rusackas** [comment]
Considering adding checkboxes for Charts/Dashboards/Queries next to the Favorites/Created/Edited tabs.

**Comment by junlincc** [comment]
@zuzana-vej does above sound like a good solution to your users? 

adding checkboxes to filter card categories in Recent section in welcome page.(e.g. check the dashboard box to view recent created/edited/favorited dashboards only)

**Comment by zuzana-vej** [comment]
Yes, users brought this up in the past, the major feedback was:
1. having the ability to select which objects to include on their welcome page (e.g. some might want to exclude queries, some charts)
2. Have the ability to see more than just 3 items, currently the "view more" goes to the search page where user needs to re-do the search (this item might not be scope of this particular roadmap item though)

**Comment by junlincc** [comment]
> Alternatively we could let them chose order, but I think keeping order and just letting them checkbox which sections to display is good.

how does adding drag and drop to checkboxes to instantly reorder section in home page sound 😆

**Comment by mihir174** [comment]
> how does adding drag and drop to checkboxes to instantly reorder section in home page sound 😆

sounds like an extremely uncommon pattern 😆 but I am looking into other ways of re-ordering and customizing the homepage layout

**Comment by zuzana-vej** [comment]
I think we should pick a simple solution (high ROI). Our users don't use welcome page really frequently. Just simple option (checkbox) what to display/not will be perfectly enough.

**Comment by zuzana-vej** [comment]
Oh I think I read the info wrongly last night. I understood that the sections on welcome page user can configure if they should see charts, queries, etc. But I think what this means is that within the Recents section at the top, user can flip between recent charts, recent dashboards, recent queries. 

If we are talking about the former (overall on the page user can decide) some simple check boxes on the page will be good enough. This would be page settings and would need to be persistent though - like user A can decide to only display "Recents" and "Dashboards" section while user B can decide to display "Dashboards" and "Queries" sections on their welcome page. I think this is separate feature.

If we are talking about the later (only the Recent section at the top) - check boxes also works and based on that the content will change.
