### ISSUE TITLE
[homescreen]show more Recent cards 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#107]
Currently, user can only view up to 6 cards in all homescreen sections. users might visit quite a few dashboards or charts everyday, especially in large enterprises that have many cross teams, it would be better to show more content in the Recent section.
<img width="1986" alt="Screen Shot 2021-01-01 at 7 53 49 PM" src="https://user-images.githubusercontent.com/67837651/103450440-4e12d200-4c6b-11eb-967d-af5c6f669a22.png">

Proposed enhancement: 
we could add pagination but will need to conduct user research to understand how far the available history should go, either by the number of recent item or time

**Comment by rusackas** [comment]
@junlincc @mihir174 For this task, should we bump up the number for now (maybe 9, or 3x3)? Or should we hold off for research around pagination/carousel/etc?

**Comment by junlincc** [comment]
@rusackas if we are bumping thumbnail card to 4 or 5 each row, it will make sense to have the consistency in recent cards, and have them be dynamic as well?
