### ISSUE TITLE
[dashboard] Dashboard Edit mode UX

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#108]
Dashboards editing UX-  improve the user experience of moving, scrolling, adding and removing components in Dashboard editing mode

**Comment by geido** [comment]
The scope is a bit large here but I'd like to take over some of this.

**Comment by junlincc** [comment]
@suddjian Aaron, would you mind being the lead of this project and collaborate with @geido Diego to breakdown the scope? 

> The scope is a bit large here but I'd like to take over some of this.

🙏🙏🙏

**Comment by suddjian** [comment]
I'm happy to be involved, but I don't think this is a project I have bandwidth to lead right now. This should probably be a SIP with collaboration between eng and design. We will need a detailed outline of how component management works in Dashboards today, a list of UX issues, and a comparison with an improved design that is more user-friendly.

I know the existing implementation uses [React DnD](https://react-dnd.github.io/react-dnd/about) which was designed to handle cross-browser drag-n-drop but I don't know much else about how it works. I suspect using browser native Drag-n-drop functionality may offer a good path forward if it has progressed far enough. That said, I haven't spent much time with either of those technologies and don't have any answers right now.
