### ISSUE TITLE
[dashboard]cloning charts on dashboard to CHARTS in editing mode 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#109]
1.  Allow users to clone charts from dashboard in dashboard Edit mode. 
2. The cloned chart will be automatically created and added the CHARTS list in editing mode. 
3. User can go explore and edit the cloned chart（from View mode or Edit mode TBD)
<img width="2029" alt="Screen Shot 2021-01-01 at 8 44 32 PM" src="https://user-images.githubusercontent.com/67837651/103450941-78b45900-4c72-11eb-9e4e-8208decd2231.png">

**Comment by geido** [comment]
Interesting one. I might try this.

**Comment by junlincc** [comment]
@geido thank you Diego, for taking this item on! it's yours. :)

**Comment by zuzana-vej** [comment]
This is a great feature and we have been hearing this from users in the past. I added the need-research label. Couple points we should discuss / think through:
1. We need to be careful about making sure it's straightforward to the users - are they editing / are they cloning. 
2. The new cloned chart is a standalone chart and will need to be edited separately in future vs. the new chart - ensure this is what user wants and they are clear on this. 
3. What guardrails / warning we want to put in place (if any) to make sure users don't create too many cloned charts which will be unused and will create clutter and confusion (warning message for example).
4. Is this intended to be used only in Dashboard edit mode or also from non-edit mode giving a non-owner of a chart opportunity to clone and re-use this chart (doubt this is what users really want to use frequently but we could ask them)

**Comment by geido** [comment]
@junlincc here some of my thoughts


Questions:
- Assuming that cloning a chart clones it immediately in the dashboard, where is that the cloned chart is going to appear? I believe we should not change the positions of the charts/components that the user has positioned in the dashboard already. Maybe positioning the cloned chart at the very bottom?
- When cloning a chart, should we allow the user to enter a name immediately, or should we just clone the chart by adding —copy to the original name? My concern with opening up a modal for editing is that a modal interrupts the flow of the user who might just want to set up the dashboard structure before having to change the chart details.
- Whatever plan we make, can we make it in a way that the roadmap item https://github.com/apache-superset/superset-roadmap/issues/84 comes as a natural consequence? :)

Opinions:
- It makes sense for the user to clone the chart in Edit mode and not in View mode.
- To make things easier, the clone option should probably be available in the Charts list only and not cloning the chart in the dashboard immediately. In that way, the user can decide where to drag and drop the cloned chart at any point in time. It is also much easier when tabs are used. Moving a chart from a tab to another is extremely painful at the moment.
- If we want the clone option to be available in an existing chart of the dashboard, we will have multiple actions for a chart, including Clone, Edit (?) and Delete (trash icon, currently the only option). It might make sense that these options appear in a dropdown menu to be consistent with the way options appear in View mode (3 dots dropdown menu, top right of the chart).

**Comment by junlincc** [comment]
> * Assuming that cloning a chart clones it immediately in the dashboard, where is that the cloned chart is going to appear? I believe we should not change the positions of the charts/components that the user has positioned in the dashboard already. Maybe positioning the cloned chart at the very bottom?

This is under the assumption that users want to clone a chart to the same tab of the same dashboard, which might not be the case. 

> * When cloning a chart, should we allow the user to enter a name immediately, or should we just clone the chart by adding —copy to the original name? 

default -copy to original name + owner's name 

> * It makes sense for the user to clone the chart in Edit mode and not in View mode. 

Need more discussion, we don't have a clear define the purpose of each mode. Hopefully not long, we can allow user in-place edit and combine these two. 

> * It might make sense that these options appear in a dropdown menu to be consistent with the way options appear in View mode 

Depends on how often users conduct those actions. but I agree!

**Comment by zuzana-vej** [comment]
Based on our user discussion last week:

- This feature is intended for Dashboard owners - when they want to copy same chart multiple times & make minor adjustments like change filter etc.
- User enters into Edit mode first and then has option to clone chart
- User will almost always want to rename the cloned chart, but by default, it can be current name plus "-- copy" or "--clone". Given that only the owners of the dashboard can do this, it's not necessary to suffix the new name of the chart with the owners name or initials. 
- Users might use same or different tab. As next level feature, it could offer user to select tab into which to clone the chart, but as first MVP, it can clone into same tab and user can move the chart.
