### ISSUE TITLE
[dashboard] color consistency through dashboard-explore flow

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#110]
1. When exploring a chart from the dashboard, to preserve the colors in the dashboard all label colors are persisted in the chart metadata, causing lots of unnecessary color metadata in the payload
https://github.com/apache/incubator-superset/issues/11674

Expected behavior: all non-relevant labels should be dropped

2. When a user clicks on Explore chart on Dashboard and got into Chart Explore, same colors on that specific chart which user saw on dashboard is not passed to chart Explore. 
https://github.com/apache/incubator-superset/issues/11674

Expected behavior: same colors should be passed 

3. User can set label color for specific series across all charts in a dashboard 
<img width="1521" alt="Screen Shot 2021-01-01 at 9 26 42 PM" src="https://user-images.githubusercontent.com/67837651/103451536-ed3ec600-4c79-11eb-9d43-f31cbd655492.png">
<img width="2013" alt="Screen Shot 2021-01-01 at 9 42 20 PM" src="https://user-images.githubusercontent.com/67837651/103451573-650cf080-4c7a-11eb-89e3-d4c00f557bfc.png">

**Comment by junlincc** [comment]
note from @mistercrunch 
"If the feature request is to have color consistency through the dashboard->explore flow, it should be implemented by passing a dashboard_id_for_context to explore, and explore can get the dashboard metadata it needs to guarantee that.

I think color consistency on that flow is nice, but not a huge priority given the complexity behind doing this nicely.

Long term solution may be around the SPA (single page app) where explore may be a huge modal on top of the dashboard in some cases, and just have that context available in Redux."

**Comment by nikolagigic** [comment]
This one looks interesting and would improve performance if I understood it correctly. I will have this one.

**Comment by lilila** [comment]
Hi @junlincc , 
The second point (explore chart) works pretty well (expect on pie charts). For me the point is to have the same label colors when charts are displayed in standalone mode!

**Comment by mistercrunch** [comment]
While the approach in 0.38 kind of worked, it a huge hack that sends big payloads (a potentially big map of all metric:color in the dashboard). These payload bloat the state in the URL and end up getting saved in the database, once saved, I think they can get out of sync with the dashboard.

I think it needs to be ripped out if it hasn't already, I liked the idea of the single-page-app solving some of this.

**Comment by zuzana-vej** [comment]
Curious if this landed on the roadmap / for when. Haven't seen more user reports on this issue, but it would still be nice to have.

**Comment by geido** [comment]
Concerning issue #13335, this roadmap item might be a good place to tackle that as well. Based on my research, when editing the properties of the Dashboard, the `label_colors` of the `json_metadata` never change, even when a new color scheme is chosen. As the `json_metadata` always has precedence, on page reload the chosen color scheme is ignored.

https://www.awesomescreenshot.com/video/2910346?key=0c18908ad8408f74c2f92465207ccc62

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/13486 @geido related request

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/5887 related

**Comment by zuzana-vej** [comment]
From the initial description:
> Expected behavior: same colors should be passed
> User can set label color for specific series across all charts in a dashboard

Adding this example about how this is confusing to user:
Dashboard chart:
![Screen Shot 2021-04-08 at 10 12 45 AM](https://user-images.githubusercontent.com/61221714/114068652-0182f800-9853-11eb-83c3-e61bc51d1597.png)

Explore chart:
![Screen Shot 2021-04-08 at 10 12 55 AM](https://user-images.githubusercontent.com/61221714/114068665-047de880-9853-11eb-8d2f-ac732afa82f8.png)

--> on dashboard see true/false colors and on chart (even though same color scheme is setup) the colors are flipped. This causes consumers easily misinterpreting the data.

**Comment by junlincc** [comment]
thanks for the additional info! 

@amitmiran137 i assume this is also bothering your users as well?

**Comment by amitmiran137** [comment]
Actually , we have currently 2 types of users :
1. Dashboard creators
2. Dashboard users
And all we are currently focus on is the end result for the dashboard users .
So in a way that issue is kind of a minor to us

Buy I believe this will become an issue eventually, once analystwill want to use the system

**Comment by zuzana-vej** [comment]
This impacts end user (Dashboard consumer) as well - whenever they go from Dashboard to Explore. (Some of our dashboard consumers do, sometimes they prefer to just share chart not dashboard, or check details of all the filters that are setup in the chart Explore which otherwise they can't see on dashboard)
