### ISSUE TITLE
[explore]customize setting for new ad hoc time picker 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#111]
1.  User can set time zone in the new time picker
2. Default value set if time zone is not selected by users
3. User can define start/end day of a calendar week 
4. User can define start/end day of a calendar quarter 
.......

related: https://github.com/apache/superset/issues/12784

**Comment by kgabryje** [comment]
I can take this one

**Comment by junlincc** [comment]
🙏! @kgabryje 

cc @zhaoyongjie

**Comment by junlincc** [comment]
@mihir174 Hey Mihir, Kamil will start implementation work soon on this item. can you help provide design? many thanks! 🙏
