### ISSUE TITLE
[explore] auto clear metrics when switching dataset

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#112]
when user switch dataset in the datapanel, Explore should auto clear all the selected values from the query using the last dataset

**Comment by pkdotson** [comment]
I might have some context on this and can take stab.

**Comment by junlincc** [comment]
i think you are the best person to own this task as well. :) thanks for taking it! @pkdotson

**Comment by pkdotson** [comment]
3-5 points
