### ISSUE TITLE
[explore]copy and paste control panel fields value 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#113]
user to be able to paste value(especially long) of metric, filter etc. in all control panel fields

**Comment by pkdotson** [comment]
I can take stab.

**Comment by junlincc** [comment]
Awesome Phillip! @pkdotson thanks for stepping in and take on more ownership! officially assigning it to you🙏

**Comment by pkdotson** [comment]
1-3 story points
