### ISSUE TITLE
[dashboard] add Explore entry point from Dashboard to create new chart

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#114]
very common question - how to add/create a new chart from Dashboard
quick win -  simple addition to have "add chart" on dashboard which will take user to Explore, and that chart can then get added onto that dashboard directly from Explore (like save and add to dashboard feature)

**Comment by geido** [comment]
Would love to take over this as I had the same feedback. This _might_ be a frontend-only implementation as all the required actions should be there already.

**Comment by junlincc** [comment]
> Would love to take over this as I had the same feedback. This _might_ be a frontend-only implementation as all the required actions should be there already.

awesome, Diego! you will be the owner of this project
