### ISSUE TITLE
[explore] resizable data and control panel 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#115]
Timeline: implement this feature along with drag and drop control panel 
Purpose: to display complete super long query values
likely keeping the current collapsible feature  

tbd....
- default width for both panels - currently 320px for both
- should we set min/max width when resizing

Designer:@mihir174

**Comment by kgabryje** [comment]
I can take this one

**Comment by junlincc** [comment]
many thanks Kamil @kgabryje 

cc @zhaoyongjie

**Comment by junlincc** [comment]
expediting this post 1.0 item to address issues in https://github.com/apache/superset/issues/12299 

cc @graceguo-supercat @zuzana-vej

**Comment by junlincc** [comment]
@ktmud @graceguo-supercat this PR is coming soon, making sure your longest column name fit and more... no need to add tooltip to all columns and metrics. 🙂
