### ISSUE TITLE
[content organization] Ability to Group Charts And Dashboards via Tags 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#116]
https://github.com/apache/incubator-superset/issues/9551

As a user, I would like to be able to logically group my charts and my dashboards. I would like either folders or to be able to filter by tags when accessing the list of charts and dashboards.

Proposed: 1. group charts and dashboard via tag, 2. filter objects by tags from list view in Charts and Dashboard

Additional context
This is a much requested feature with many closed issues:

Allow users to tag dashboards from November, 2017
Folder structure for dashboard and slice from December, 2017
Organising Charts List from April, 2019
Group Dashboards folders or tags from April, 2019
Ability to Tag Charts for Easy Filtering
There's even a PR but it appears that it may need to be rewritten to be accepted:
Tagging frontend

**Comment by ktmud** [comment]
It would be nice to implement hierarchical folders as well. We may also want enable access control by folders.

**Comment by mistercrunch** [comment]
FYI there's an implementation of tags behind a feature flag that @betodealmeida implemented. I think it may be backend only and that the frontend part lived only in a fork at Lyft.

We spoke a lot about this in SIP-34, people didn't seem to like tags much, and seemed to prefer the idea of bringing in a new meta-object (call it Workspace, Project, Team, or whatever). Clearly this meta-object would be contain curated list of object (dashboards, charts, queries, ...), markdown and maybe other things. If we want team to be able to curate the lists, integrate charts and offer flexibility around the layout of all this, it starts to sound a lot like some sort of special (or not-so-special) dashboard.

Given that, personally I think the best step forward is to create a new native dashboard component called "object collection" or similar. It's unclear to me whether we need to make that dashboard special (as in flag it as such and present it differently, or just have it be a dashboard that happens to contain object collections).

A side conversation was around whether/how these meta-objects relate to RBAC. Can I give someone access to a collection and that effectively gives them access to underlying objects? No clear answer on this.

**Comment by mihir174** [comment]
@junlincc 
@Steejay did some awesome work on grouping saved queries with "Groups" that function like folders - users responded very well to this. We can run user tests on a few different options like tags, folders etc but I think following the sql lab model will be good for consistency across the product

**Comment by Steejay** [comment]
Yup! This will be an effort we will begin soon to explore object grouping starting w queries. We'll keep all object types in mind when designing this pattern while working w the community on this. 
cc @yousoph

**Comment by junlincc** [comment]
@Steejay great to hear to progress you made, given all the research your team has done, it will make sense for you guys to take on this project. I'm closing this item, feel free to add to your roadmap.

**Comment by rubenssoto** [comment]
Hello Guys,

Dou you have any updates on this issue?

We are testing BI solutions and this is a feature that our users want.

thank you
