### ISSUE TITLE
[annotation]annotation creation new UX/UI

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#117]
create annotations in the context of the visualization you want them on
annotation layers live in explore/ wherever charts are edited
<img width="2045" alt="Screen Shot 2021-01-02 at 1 33 04 PM" src="https://user-images.githubusercontent.com/67837651/103466991-210fff00-4cff-11eb-8a05-e86c4d93e163.png">

designer: @mihir174
developer:@agatapst

**Comment by agatapst** [comment]
I'd be happy to work on this!

**Comment by junlincc** [comment]
thank you so much for taking this on! 🙏

 @mihir174
