### ISSUE TITLE
[dashboard] List owners on dashboard

### ISSUE THREAD

**Issue by zuzana-vej** [apache-superset/superset-roadmap#119]
### Motivation / Problem to Solve
As a dashboard consumer, I would like to know who created the dashboard, so that I know who to contact with any questions. Currently, unless team adds markdown on the dashboard, users have no way to find this information. 

### Proposed Functionality
Needs design input, but somewhere on the top right of the dashboard it could either display icon for "dashboard owner" and on hover list of the owners, or directly display list of owners. Some dashboards have 1 owner but some may have as many as 10 owners, so probably not all of them should be listed (they could be displayed on hover).

**Comment by junlincc** [comment]
+1 on this

**Comment by junlincc** [comment]
closing in favor of Epic https://github.com/apache-superset/superset-roadmap/issues/144
