### ISSUE TITLE
[global] Mono repo migration 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#122]
We are setting mono-repo migration as our top priority for Q1 2021, the current work flow is severely blocking development ,releasing and QA process. 
SIP and plan will be provided soon.

**Comment by amitmiran137** [comment]
This is a great top priority! 🎩 
having core modules in a separated repo makes it impossible to work.

we should also consider having the core plugins (legacy, echarts, deckgl and etc') to stay in [superset-ui ](https://github.com/apache-superset/superset-ui) demonstrating an independent plugins repo, same as [superset-viz-plugins](https://github.com/nielsen-oss/superset-viz-plugins/)
