### ISSUE TITLE
[global] Replace remainder of React Bootstrap with AntD

### ISSUE THREAD

**Issue by rusackas** [apache-superset/superset-roadmap#123]
### Motivation / Problem to Solve
As has been previously acknowledged by the community, by SIPs, and by progress already made in the effort, there is a need to remove React Bootstrap from our product, along with any CSS it uses, and replace it with AntD (and/or possibly supporting or related packages), and build these replacement components in a manner that is consistent in design, utilization, and code structure. This will enable a stronger relationship between frontend engineering and the emerging Superset design system, aid in navigation of the codebase, aid in ease of engineer onboarding, drive UI/UX consistency, and increase reliability/testability of UI work via consolidated styling, specimens (i.e. Storybook), and unit/integration tests.

### Proposed Functionality

Some of this work is in progress already, with PRs on hold until 1.0.0 is released, but this is _approximately_
 the scope of work:

<table>
<tr>
<td><b>React-Bootstrap</b></td>
<td><b>AntD</b></td>
</tr>
<tr>
<td>Alert</td>
<td>Alert</td>
</tr>
<tr>
<td>Col<br>Row</td>
<td>Col<br>Row</td>
</tr>
<tr>
<td>Nav<br>NavBar<br>NavItem<br>NavDropdown</td>
<td>Menu<br>Menu.Item</br>Menu.SubMenu<br />Menu.ItemGroup<br />Menu.Divider</td>
</tr>
<tr>
<td>TabContainer<br>TabPane<br>TabContent</td>
<td>Tabs<br>Tabs.TabPane</br></td>
</tr>
<tr>
<td>Radio</td>
<td>Radio</td>
</tr>
<tr>
<td>Form<br />FormGroup<br />FormControl<br />FormControlProps<br />ControlLabel<br />HelpBlock<br />InputGroup</td>
<td>Form<br />Form.Item<br />Form.List<br />Form.ErrorList<br />Form.Provider</td>
</tr>
<tr>
<td>Panel<br />Panel.Heading<br />Panel.Body<br />Panel.Collapse</td>
<td>Collapse<br />Collapse.Panel</td>
</tr>
<tr>
<td>Button<br />ButtonGroup</td>
<td>Button</td>
</tr>
<tr>
<td>DropdownButton</td>
<td>Dropdown</td>
</tr>
<tr>
<td>Label</td>
<td>Typography</td>
</tr>
<tr>
<td>Well</td>
<td>Card</td>
</tr>
<tr>
<td>ListGroup<br />ListGroupItem</td>
<td>List</td>
</tr>
<tr>
<td>Collapse</td>
<td>Collapse</td>
</tr>

</table>

Each component we implement should trigger an audit of competitive "species" within the codebase, in an effort to reduce/consolidate components. Each new component should have tests, stories, and styling following more current and emerging patterns as established in existing AntD-based componentry.

Special hat tip to @michael-s-molina for generating the audit.

**Comment by michael-s-molina** [comment]
@rusackas Can you close this one?
