### ISSUE TITLE
[Epic] Replace/convert react-bootstrap to AntD

### ISSUE THREAD

**Issue by eschutho** [apache-superset/superset-roadmap#127]
### Motivation / Problem to Solve
We are moving toward AntD for a more modern approach and would like to be able to remove old libraries and have code consistency.

### Proposed Functionality
Remove react-bootstrap library and have all components use AntD instead.

**Comment by junlincc** [comment]
Duplicate of [global] Replace remainder of React Bootstrap with AntD
