### ISSUE TITLE
[Epic] Bring Superset UI into Superset

### ISSUE THREAD

**Issue by eschutho** [apache-superset/superset-roadmap#128]
### Motivation / Problem to Solve
Merge files, keep in central location, etc. @junlincc 

### Proposed Functionality
*** How should the proposed solution work? What are the user expectations? Describe the main use cases or user flows. ***

**Comment by junlincc** [comment]
duplicate of [[code_hygiene] Mono repo migration  ](https://github.com/apache-superset/superset-roadmap/issues/122)

Some implementation has already started by Nielsen team
