### ISSUE TITLE
[Dashboard] Clone a dashboard

### ISSUE THREAD

**Issue by rusackas** [apache-superset/superset-roadmap#142]
### Motivation / Problem to Solve
Right now, if you want to riff on someone's dashboard, you have to export it, import it, and then you can get to work. Wouldn't it be great to click a "Clone dashboard" button and just get to work? I think so too.

### Proposed Functionality
*** How should the proposed solution work? What are the user expectations? Describe the main use cases or user flows. ***

**Comment by junlincc** [comment]
we can do it in Q5

**Comment by rusackas** [comment]
Tag as `low-impact`

**Comment by ktmud** [comment]
Don't we already have a "Save as..." button?

<img src="https://user-images.githubusercontent.com/335541/104663609-37fd0c80-5682-11eb-9276-94814135bd6c.png" width="250">

You can even duplicate all charts:

<img src="https://user-images.githubusercontent.com/335541/104663689-624eca00-5682-11eb-840c-fa50b5f18d4c.png" width="500">


A small task we can do, however, is add current user name to the default title:

<img src="https://user-images.githubusercontent.com/335541/104663986-00db2b00-5683-11eb-8aeb-b62615c73916.png" width="500">

**Comment by junlincc** [comment]
what Evan meant is, bypassing the entire saving flow in the modal. one click to make a copy. User can later edit the dashboard name etc.

**Comment by ktmud** [comment]
I'm not sure bypassing this modal adds any value...

**Comment by junlincc** [comment]
well, that's a Q5 item.

**Comment by rusackas** [comment]
Maybe a semantic change would make me happy... changing "Save as" to "Save a copy" to get a little closer to how google solved this. I like the idea of adding the name!
![image](https://user-images.githubusercontent.com/812905/104666427-bb216100-5688-11eb-9b6f-360a5b7a53f4.png)

**Comment by junlincc** [comment]
+1 on both of your ideas 😁

**Comment by rusackas** [comment]
While this might have a couple tasks, it probably doesn't warrant being a roadmap Epic. I'll just close this, and we can open some little issues on the repo to tackle both points. Thanks for playing :D
