### ISSUE TITLE
[Dasbhard] New dashboard tabs should go immediately into edit mode

### ISSUE THREAD

**Issue by rusackas** [apache-superset/superset-roadmap#143]
### Motivation / Problem to Solve
Right now you have to click the + button, double click the tab to reveal the input, then triple click the text to highlight and delete it. Clicking the plus button should bring you into an empty input with "Tab title" as _placeholder_ text, so you can start typing immediately.

### Proposed Functionality
*** How should the proposed solution work? What are the user expectations? Describe the main use cases or user flows. ***

**Comment by junlincc** [comment]
completed
