### ISSUE TITLE
[dashboard] view and add new dashboard mode UI change

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#144]
Below changes are gonna take place in the create empty dashboard view

1. Move favorite "Star" before the title
2. Default title for new dashboard styling change 
3. DRAFT icon stying change
3. Display dashboard owner's initial to the right, hover to see full name in tooltip
4. Add a Welcome message in the empty dashboard
5. In the message, add an entry point to Explore to create a new chart 

https://projects.invisionapp.com/share/BNVBOEJRWQ2#/screens/398392331

Old:
<img width="1018" alt="Screen Shot 2021-01-17 at 4 24 38 PM" src="https://user-images.githubusercontent.com/67837651/104862780-8871a580-58e0-11eb-8092-d0350807952c.png">

New:
<img width="1304" alt="Screen Shot 2021-01-17 at 4 14 43 PM" src="https://user-images.githubusercontent.com/67837651/104862670-2b75ef80-58e0-11eb-82c1-7c6693461ab0.png">

Related to https://github.com/apache-superset/superset-roadmap/issues/119

**Comment by junlincc** [comment]
@mihir174 if design effort takes more than 1 story point, we can start implementation directly

**Comment by zuzana-vej** [comment]
Great features planned!

> 4. Display dashboard owner's initial to the right, hover to see full name in tooltip

Note, some dashboards can have multiple owners. Assuming similar design as on View Dashboards would be used. 
![Screen Shot 2021-02-07 at 6 05 17 PM](https://user-images.githubusercontent.com/61221714/107167936-0fa9ba80-696f-11eb-8661-f68438a4b93b.png)

Another commonly requested item is "Display last updated date" I know this might be hard to fit on the dashboard view but in case you see value in it and find a good place from design perspective (it could be small icon and hover-over to see last updated). While just simply last updated isn't always best indicator of a dashboard quality, it's a good piece of metadata.

**Comment by graceguo-supercat** [comment]
@junlincc During the Transition time for dashboard filter migration, i feel it is important to let everyone see the dashboard owners list. Because only dashboard owner can preview the converted filter components. Could we prioritize this feature:

**Display dashboard owner's initial to the right, hover to see full name in tooltip**
