### ISSUE TITLE
[team] remove Ville from all tasks as soon as possible so that he can LEAD high impact projects and rest

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#145]
this is a real roadmap blocker and i would like to make it high priority for myself in Q1 😁
remove Ville from all tasks, including 
1. CS 
2. bug fixing
3. UI feature development 
4. refactoring work 
5. CI optimization
6. release management 

Project to lead:
1. monorepo
2. non-temporal chart integration 
3. v2 chart data API (at least non-aggregating metrics)
4. dynamic controls
5. crossfiltering. 
6. community individual contributors team development 

cc @rusackas

**Comment by ktmud** [comment]
It's nice to highlight important projects, but we probably should't add company-specific operational items to the superset-roadmap.

**Comment by junlincc** [comment]
You are absolutely right. Please note that most of the projects listed above are community collaboration, not corporate specific. Cross org team operation does becomes a big criteria for success of those items.
