### ISSUE TITLE
[dashboard] set, clone and share native dashboard filter set

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#146]
1. User filter sets 
- the ability to save a group of filters together as a set and switch between sets to in order to view the same dashboard in different filter configs
- the ability to save a group of filters together as a set and apply the same set on different dashboards 
- the ability to save a group of filters together as a set and share the set between users 

2. Scheduled dashboard emails with a chosen user filter set

**Comment by junlincc** [comment]
@amitmiran137 Hey Amit, would you mind assigning yourself to this item? we will not need a sip to kick it off, but I do want to allocate resources from my end to make sure this project complete on-time. lmk~ thanks!

**Comment by amitmiran137** [comment]
Sure assign this to me . I can't assign to myself

**Comment by amitmiran137** [comment]
adding some requirements to user filter sets

1. when a user saves a filter set it is only available to the specific user
2. there should be an indication to differentiate between dashboard and user filter set 
3. user should be able scheduled Dashboard emails with a specific dashboard/user filter set
4. user should be able to create/remove/modify his personal filter sets
