### ISSUE TITLE
[dashboard&explore] bumping react-dnd library from 2.5.4 to latest⚠️

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#148]
Superset Dashboards drag and drop functionalities is built on a react library called `[React-dnd]`(https://www.npmjs.com/package/react-dnd) using HTML5 drag and drop API. Since the earliest implementation of `v2.5.4` 3 years ago, Superset has not updated this dependency.  
Though the older version can still support drag and drop motions in Dashboards edit mode, we started seeing more and more issues and limitations in this area as we attempt to implement new features in Dashboards and Explore.  

After discussion, instead of further investing time and effort by adding more 'patches' upon current version, we decided to bump the dependency to latest on the awareness of severe risks and regressions could be introduced, as we are nine major versions behind - `11.1.3.` We will open a feature branch for this experiment to keep master stable and postpone all the drag&drop projects(Explore d&d query, Dashboard UX 3.0) in Superset until the upgrade is completed. 

related roadmap item: 
https://github.com/apache-superset/superset-roadmap/issues/108
https://github.com/apache-superset/superset-roadmap/issues/91

cc @graceguo-supercat @mistercrunch @suddjian

**Comment by suddjian** [comment]
Oh man I never noticed we were so far behind. This looks like a good plan!

**Comment by junlincc** [comment]
roadmap item completed. i guess we are ready to go full speed dashboard 3.0 and explore drag and drop :)
