### ISSUE TITLE
[i18n] Clean up translation strings

### ISSUE THREAD

**Issue by ktmud** [apache-superset/superset-roadmap#153]
### Motivation / Problem to Solve

To have more accurate translations, translation keys need be unique to its context and should not be reused in different context. For example, in Chinese, you don't just say "Next" (下一个）in most context，but always be specific of next of what (e.g. ”Next page" (下一页)，Next picture (下一张)).

It's even more problematic to concat translated strings, e.g.:

```
_("You don't have the rights to ")  + _("alter this ") + _("dashboard"),
```

This may [save some translation strings](https://github.com/apache/superset/pull/4346#discussion_r166836344) but will make it more difficult to translate when a language has a different [word order](https://en.wikipedia.org/wiki/Word_order) than English.

### Proposed Functionality

- Step 1: Clean up all concatenated translation strings
- Step 1.5 (Optional): Update i18n solution, make it possible to fallback to English translated strings.
- Step 2: Replace all translation keys with unique, contextualized keys. E.g.
   ```
    _('global.menu.Charts')
   ```

**Comment by junlincc** [comment]
+1

**Comment by ktmud** [comment]
Step 1 should be pretty easy.
