### ISSUE TITLE
[Epic] chart and dashboard versioning

### ISSUE THREAD

**Issue by krsnik93** [apache-superset/superset-roadmap#156]
### Motivation / Problem to Solve
It would be immensely useful to have a way to version charts and dashboards and then rollback or fast forward from one version to another as needed. The way to do this currently is by using Superset's REST API to import/export metadata and then versioning with Git.

### Proposed Functionality
Every modification on a chart or a dashboard would result in a new metadata version which would be stored in Superset's backend database. Then it should be possible for users to change versions via GUI, with the latest version being default.

**Comment by aseem-poloniex** [comment]
Does this functionality exist in Apache superset?
