### ISSUE TITLE
[Dashboard] make chart elements responsive on resize in dashboard 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#157]
Ideally, the chart itself and all its elements should be responsive on resize in a dashboard. 
to name a few- show or hide elements, scale, number of ticks, size of the labels, position and grouping of the legend....could even be the orientation of the chart(e.g. horizontal vs vertical bar). 

![ezgif-3-40947beb00be](https://user-images.githubusercontent.com/67837651/108918850-e2a00d80-75e6-11eb-9000-d86ac32db662.gif)

We have two options
1. migrate all legacy and customized charts to Echarts first, implement changes at chart type(composition, time series,  distribution, relationship, geospatial) level.  
But it will likely take up to a year to finish the project. 
2. implement changes individually to all existing charts(40+ of them) now. but the enhancement will likely be a waste after Echarts migration. 
Alternative
a. add min width and height (not an optimized UX but can stop some bleeding easily)
b. allow user to configure at chart level (more work and more work going to be wasted) 

Proposed solution: combination 1 & a

Adding some screenshots to explain why we need this change....

<img width="309" alt="Screen Shot 2021-02-23 at 2 28 31 PM" src="https://user-images.githubusercontent.com/67837651/108918871-ec297580-75e6-11eb-9897-33faba60cc4b.png">
<img width="807" alt="Screen Shot 2021-02-23 at 2 28 10 PM" src="https://user-images.githubusercontent.com/67837651/108918881-f3508380-75e6-11eb-8f06-dace91df5a89.png">
<img width="246" alt="Screen Shot 2021-02-23 at 2 27 18 PM" src="https://user-images.githubusercontent.com/67837651/108919391-c486dd00-75e7-11eb-8bcc-3f9b42c04a7c.png">
<img width="469" alt="Screen Shot 2021-02-23 at 2 29 08 PM" src="https://user-images.githubusercontent.com/67837651/108919393-c650a080-75e7-11eb-9e58-5b70feb2fc3e.png">

**Comment by junlincc** [comment]
@mistercrunch ^^^^

**Comment by maloun96** [comment]
@junlincc In my opinion the best option is to let the user set min-width and min-height and save it to the database. I prepared a small demo in the video.

https://user-images.githubusercontent.com/8277264/108991410-bea10280-76a0-11eb-9419-39ca2d323140.mov

**Comment by villebro** [comment]
I think it would be nice to provide good defaults for charts where the wheels are known to fall of at some certain threshold. Those could be overridable, but I think the defaults should mostly just work.

**Comment by maloun96** [comment]
We can't set default some width and height if 1 chart has a longer label and other shorter but will have the same default width / height

**Comment by villebro** [comment]
I'm thinking more in terms of automatically moving/hiding legends if the charts gets too cramped etc, like in Junlin's Highcharts example. As an example, the same can be applied to labels being automatically hidden on Pie charts if the `min(width, height)` falls under some critical threshold to make sure the chart retains some minimum level of usefulness.

**Comment by maloun96** [comment]
I got your point. It will take some time to try for each chart. For example, for the heatmap, we can hide y-axis labels.

https://user-images.githubusercontent.com/8277264/109011949-24e64f00-76ba-11eb-857e-a4501d617303.mov

**Comment by junlincc** [comment]
Thank you @maloun96 for prototyping. Our goal is to put less burden on users, setting height and width on Dashboard doesn't seem to be aligned ..😔
Let's break this epic down and tackle each case separately.
1. labels size on sunburst, Sankey etc. - definitely responsive. user should be no need to set size at all
2. number of ticks - prefer dynamic but allow user to set preference 
3. legend - should be first to hide when resizing, or no show at all by default on dashboard. 
4. x tick label - rotate and truncated on resize, set max % in chart 
....

I will need some time to come up with more cases
