### ISSUE TITLE
Superset Component library - Phase 1

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#23]
## Motivation / Problem to Solve
Make development easier and faster by building out a component library that can be used to (re)build Superset UI.

## Proposed solution
Update 5 most-used components to follow updated Component strategy

**Comment by junlincc** [comment]
Phase 1 completed below 
Menu/Menu item
Dialog
Modal
Popover
Dropdown
react-table
Select
Dropdown 
tooltip
.......

Not sure if I covered everything you did, really great work Kamil! @kgabryje 

Phase 1 is successfully completed
