### ISSUE TITLE
Global Async Query Support [SIP-39]

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#24]
## Motivation / Problem to Solve
See SIP for details
[SIP-39](https://github.com/apache/incubator-superset/issues/9190)

## Proposed solution
See SIP for details
[SIP-39](https://github.com/apache/incubator-superset/issues/9190)

**Comment by bkyryliuk** [comment]
This may be a blocker:
https://github.com/apache/incubator-superset/issues/10530

**Comment by willbarrett** [comment]
Above issue is closed - let us know if it's still a blocker.

**Comment by bkyryliuk** [comment]
It is closed for the current superset celery workers. Shifting all explore requests to the celery would be a different type of load & will most likely require nullpool for the Superset (metadata ) DB interactions. I think it will work, however it will require a bit of work on making it reliable & fast.
