### ISSUE TITLE
Home Screen MVP

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#32]
## Motivation / Problem to Solve
When a user logs into Superset, they are taken to the Dashboards list as a "Welcome" page. Modern web applications often have a home page that can serve as the information hub and jumping point for the user

## Proposed solution
Implement a home screen as the default page that users land on after sign in. In the MVP version this is a page with a static structure, but the information displayed is specific to the user, and includes objects relevant for the user (recently created, viewed, etc) in a card view format. Excludes activity stream.

**Comment by junlincc** [comment]
completed for 1.0~ ♥️
