### ISSUE TITLE
Date picker UX/UI improvements

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#34]
## Motivation / Problem to Solve
The date picker UI is used when a date range input is required. The Current UI's design is outdated and the functionality misses some options that users need for advanced use cases.

## Proposed solution
- NO new functionality
- UX quick wins, steer towards SIP-34 design if easy
- make date mini language more discoverable and accessible
- make sure the time anchor and duration are always clear to the user

**Comment by junlincc** [comment]
link to miro board. please comment 
https://miro.com/app/board/o9J_kiQxGIU=/

**Comment by junlincc** [comment]
completed for 1.0~ 🎉
