### ISSUE TITLE
Echarts integration(3 charts)

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#48]
## Motivation / Problem to Solve
From the SIP: "Superset has also grown to support 30+ visualizations that consists of a patchwork of libraries that are rooted in a vast dependency tree. This creates visual inconsistencies and many challenges around keeping up with different projects, people, APIs, code styles, levels of quality, ..."

[SIP-50](https://github.com/apache/incubator-superset/issues/10418)

## Proposed solution
From the SIP: "Standardize on using ECharts! as our primary visualization library for core visualization that ship with Superset."

[SIP-50](https://github.com/apache/incubator-superset/issues/10418)

**Comment by junlincc** [comment]
completed for 1.0 ♥️
