### ISSUE TITLE
Implement Annotations in Echarts based visualizations

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#56]
## Motivation / Problem to Solve
Users can layer additional data on a chart using Annotations. This feature is not supported in ECharts. As charts are migrated to ECharts, Annotations need to be re-implemented

## Proposed Solution
- Re-implement Annotations in new charts
- Improve Annotations UX as part of the work

**Comment by junlincc** [comment]
Completed for 1.0
