### ISSUE TITLE
Make list view filter states sticky across sessions

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#59]
## Motivation / Problem to Solve
The new list view UI allows users to filter lists in more complex ways. However, these filters are reset every time the user starts a new session, and the user sees the unfiltered list as a default in each new session.

## Proposed Solution
When the user revisits a list view in a new session, the list should be in the state it was at the end of the previous session. I.e. list filter states need to be "sticky" between sessions.

**Comment by zhaoyongjie** [comment]
Hi @junlincc , I have some Superset experience, can I help with this feature.

**Comment by junlincc** [comment]
coooool! thank you @zhaoyongjie for committing to making this feature happen. @benceorlai if thats ok with you, i will work w Yongjie directly on this feature enhancement.
