### ISSUE TITLE
Inform user of potentially breaking changes when editing a Dataset from the Explore > Edit Dataset menu

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#64]
### Motivation / Problem to Solve
As discussed in [this issue](https://github.com/apache/incubator-superset/issues/11478), when the user edits the Datasource in Explore, they may inadvertently edit the underlying dataset. The [potentially unintended] change in the Dataset can break other charts that are based on the same dataset. This outcome is likely to happen in systems with a large number of users and charts.

### Proposed Functionality
- Make the existing warning in the UI more prominent to let the user know of potentially breaking changes ahead
![image](https://user-images.githubusercontent.com/8263072/97861826-3d6ccc80-1cb9-11eb-88f5-ef2c89d40a11.png)
- When the user is about to save changes to the Dataset, show a prompt that informs them of breaking changes and the number of charts affected. For example: "You are about to save changes to this Dataset. There are [number] charts using this Dataset and your changes may break those charts. Are you sure you want to proceed?" Apply the changes only when the user positively decides to proceed after the warning

**Comment by zuzana-vej** [comment]
related issue https://github.com/apache/superset/issues/11478
