### ISSUE TITLE
Group/Employee Permission Hierarchy

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#66]
### Motivation / Problem to Solve
Due to data sensitivity, compliance purposes and/or security reasons, business units and/or employees are restricted to certain types of information in the company.

Data access/filtering is determined by business group hierarchy or by employee hierarchy.
The current user permission setting requires organization to reconfigure or create unique user roles to fit different hierarchy structures per business unit and/or end-user customers.

Request from @ AZsineadcheung

**Comment by AZsineadcheung** [comment]
Confirming I can comment @benceorlai

**Comment by pradhangn** [comment]
I would request ability for stronger control of charts and dashboard permissions:
- User group A and B both have access to datasets 1 and 2
- User group A should not be able to see charts or dashboards made by user group B on datasets 1 and 2

This allows the following use cases:
Common datasets used across multiple teams or even organizations on a single superset instance. Currently we have to have 2 separate superset instances even when deploying the same datasets for 2 independent organizations or groups.
