### ISSUE TITLE
Native dashboard filter component

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#7]
## Motivation / Problem to Solve
See SIPS 9,25,49
https://github.com/apache/incubator-superset/issues/5925https://github.com/apache/incubator-superset/issues/8452https://github.com/apache/incubator-superset/issues/10285

## Proposed solution
Native filter component - feature parity with the current filter chart

**Comment by junlincc** [comment]
Follow up tasks can be found https://github.com/apache/incubator-superset/issues/12148
closing and marking this project Completed for 1.0
