### ISSUE TITLE
[homescreen] smaller cards, dynamic cards on homescreen

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#72]
### Motivation / Problem to Solve
*** Why do you propose to work on this project? What is the business problem that needs to be solved? What are the user pain points or needs? ***

### Proposed Functionality
*** How should the proposed solution work? What are the user expectations? Describe the main use cases or user flows. ***

**Comment by ktmud** [comment]
This should apply to thumbnail view on other CRUD pages as well.

**Comment by rusackas** [comment]
Is this effectively the ability to turn off thumbnail display?

We should use the thumbnails feature flag here, and if the flag is False, don't show the placeholder thumbnails... just the slimline cards.

**Comment by junlincc** [comment]
> We should use the thumbnails feature flag here, and if the flag is False, don't show the placeholder thumbnails... just the slimline cards.

Yes!
