### ISSUE TITLE
[explore] chart SAVE and Delete flow

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#75]
save enhancement: https://github.com/apache/incubator-superset/issues/11748

delete: ability for user who is the chart owner to delete chart directly from the explore tab

**Comment by geido** [comment]
I had similar feedback so I'd like to take this one.

**Comment by junlincc** [comment]
> I had similar feedback so I'd like to take this one.

SGTM~ thank you for taking it on!
