### ISSUE TITLE
[explore]Add "metric" to show actual value of column, i.e. no aggregate #7172

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#87]
https://github.com/apache/incubator-superset/issues/7172

Non-aggregating metrics: a really simple feature that could be hacked on top of 1.0 fairly easily, but probably needs some rethinking to make it a truly clean UX (there needs to be a non-invasive warning telling the user that things will go terribly wrong if they claim that a non-aggregated field is pre-aggregated).

**Comment by lmatei80** [comment]
Can you give me a hint on where the hack can be implemented in the code? This scenario is a blocker for me in a use case and I would like to see if it would work right without that aggregation.
