### ISSUE TITLE
[chart] Dynamic controls UI reacts to data and chart types

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#88]
Dynamic controls. The static nature of the current control panel is really holding us back, and needs to be fully revamped for 2.0.

As a Superset user, 
- when I explore my data using a line chart, I do not need to see the time section when there's no time columns in my dataset. 
- when I explore my data using a bar chart, group(series) limit should not show when no group-by is selected. 
- after I select a metric, I expect sort-by control is set by said metric by default 
- when I visualize dataset in Explore, I expect the Superset to offer me a row limit range depends on the dataset 
- when I open Explore, only the basic controls show by default (e.g. x-axis and y-axis), as I drop different measures and columns into each field, it expand for customize setting(maybe). 
- when time columns are available in a dataset, show advanced analytics and predictive analtics options 
- when bar chart is selected, the cosmetic control setting that only applies to line/area should not show 
<img width="397" alt="Screen Shot 2021-04-21 at 4 42 42 PM" src="https://user-images.githubusercontent.com/67837651/115635578-e25b8000-a2c0-11eb-86c0-4318947130dd.png">

others.. 
single series customizable - making possible to customize a single series, e.g. making one series(new york) a line, the other an area graph on the same chart

**Comment by ktmud** [comment]
What does "dynamic" mean?

**Comment by villebro** [comment]
The way I see it, the intent here is twofold:
- Make the control panel less static by nature. Currently the majority of control panels are showing all options all the time, with fairly simplistic grouping. It would be preferable to have a more modular design, where options are only exposed if relevant. For instance, the series limit should not be visible unless a groupby is active on timeseries charts. This will make it possible add customizability without degrading the UX.
- Make the control panel aware of data coming back from the chart data request. For instance, on timeseries charts, the series names from the groupby are not known prior to a completed chart data request. To make it possible to customize series properties for specific series (series type, number format, color, left/right y-axis etc), data from the request needs to be made available to the controls, probably via a hook.

**Comment by ktmud** [comment]
Makes sense. For the first item, it is already possible with the `visibility` hook and `mapStateToProps` (e.g. the query mode switch in table viz), but the API is kind of ugly. Happy to see a full revamp in this area.

**Comment by villebro** [comment]
Thanks, I'll take a look at how table viz does it.
