### ISSUE TITLE
Improve UX for Dashboard filter application status

### ISSUE THREAD

**Issue by benceorlai** [apache-superset/superset-roadmap#9]
## Motivation / Problem to Solve
The current "teeth" are not a good UX for seeing which filters are applied to a chart. See SIP-49 for details. https://github.com/apache/incubator-superset/issues/10285

## Proposed solution
- view the filtering status of each chart
- visual validation of filtering event 
- remove the “Teeth”

**Comment by junlincc** [comment]
completed but duplicate
