### ISSUE TITLE
[code quality] engineering-focused code quality work

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#90]
to improve product stability and unlock greater future development velocity
scope could include SPA, mono-repo, testing, refactoring, or anything else that we deem is an important code quality or engineering improvement. TBD

**Comment by junlincc** [comment]
re:mono-repo @ktmud 
manual testing on the data viz PRs in `Superset-ui` has been a pain lately and i can imagine there's a bigger pain for the developers. you have done quite a lot heavy lifting work towards the direction of migrating repo. so I wonder if you have any further plans of it? we are happy to allocate resource to make it happen with your support.

**Comment by ktmud** [comment]
I'm afraid I won't have time to do that myself next year. There are too many moving pieces. Happy to provide support wherever I can.
