### ISSUE TITLE
[chart]show no legend by default for all charts 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#92]
- users usually instinctively hover first to see chart details, especially if there are crazy amounts of series on a chart, it also runs out of color from the color theme when it reaches 10+ series. 
- to leave more real estate for the charting area as now the new `DATA` takes up 20% of the space by default 
- to keep it consistent across all chart types and libraries 
- aesthetics and cleanness

**Comment by nikolagigic** [comment]
I can take this one

**Comment by junlincc** [comment]
@maloun96 moving this one to you~

**Comment by maloun96** [comment]
@junlincc ok.

**Comment by junlincc** [comment]
all chart no legend by default ✅
multiple legend position(top, bottom, side) scrollable in echarts ✅
closing item as project is completed

minor cosmetic issues found in https://github.com/apache/superset/issues/12776

thanks @maloun96 @villebro !
