### ISSUE TITLE
[design]better treatment for long titles 

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#94]
coming up with better treatment for long titles in homepage cards, dashboard, charts, and filter indicator etc. 
to balance showing full title without restriction and saving real estate on the objects 

cc @mihir174

**Comment by junlincc** [comment]
Displaying super long metrics in Data panel and Control panel fields

**Comment by zuzana-vej** [comment]
Is this just about titles or are we considering Shorter title (limited length) plus a subtitle (also limited length) which can be displayed below the title? We could get inputs from users. I sense that many of our long title could be split into title and sub-title, where both are displayed with different font size. We are probably okay with keeping just titles as long as they can continue to be long, but it could be worth to consider if title + subtitle are a better option.
