### ISSUE TITLE
[dashboard]filter indicator to include a collapsible section for pre-configured filters  

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#96]
![Group 67](https://user-images.githubusercontent.com/67837651/101447345-e373ae00-38d9-11eb-9cde-27d46c062f77.png)

Pre-configured means ad hoc filters added to the charts from Explore 

<img width="417" alt="Screen Shot 2020-12-07 at 10 18 53 PM" src="https://user-images.githubusercontent.com/67837651/101447500-36e5fc00-38da-11eb-8cb3-6db5f94d985b.png">

**Comment by agatapst** [comment]
I can try this one

**Comment by junlincc** [comment]
> I can try this one

This is ideal! thanks Agata for taking this one on! 🙏🙏

cc @mihir174
