### ISSUE TITLE
Adjustable Column Width in Results

### ISSUE THREAD

**Issue by yousoph** [apache-superset/superset-roadmap#98]
https://github.com/apache/incubator-superset/issues/10333

**Comment by st2654** [comment]
Hi @yousoph, Is there any plan to get this issue resolved? 
I am new to this Github "Jira Style" Roadmap . Can I contribute and get this merged and released?

**Comment by yousoph** [comment]
Hi @st2654! Yes, your contribution here would be amazing! 

@Steejay has done some thinking and written up some specs around default widths, min and max widths, truncation, interactions, etc. That can all be found here: https://www.figma.com/file/7fyjKdVfnDv9mZ6mXHWAhl/SQL-Results-Column-Resizable?node-id=128%3A9368 

Please feel free to reach out to either of us if you have any comments, questions, suggestions etc 😄
